version: "3.8"

services:
  app:
    image: grima
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 3001:3001
    command: "just valgrind"
    tty: true
    stdin_open: true
    environment:
      - PORT=3001
      - DATABASE_URI=postgres://postgres:postgres@postgres:5432/grima_development

  postgres:
    image: postgres:15.4
    volumes:
      - development_data:/var/lib/postgresql/data
      - ./sql:/scripts
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=grima_development

volumes:
  development_data:
